[profile.default]
src = "contracts"
out = "contracts-out"
libs = [
    "lib"
]

remappings = [
    '@layerzerolabs/oft-evm/=lib/layerzero-v2/packages/layerzero-v2/evm/oapp/contracts/oft',
    '@layerzerolabs/oapp-evm/=lib/layerzero-v2/packages/layerzero-v2/evm/oapp/contracts/oapp',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
]

# to support chains running older evm / geth forks
evm_version="Istanbul"